
#Dimensional shard ore generation
[worldgen]

	#Other Dimensions
	[worldgen.dimensions]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 0
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 10
		#Min height
		#Range: -512 ~ 512
		oreMin = -65
		#Max height
		#Range: -512 ~ 512
		oreMax = -65

	#Overworld
	[worldgen.overworld]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 0
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 5
		#Min height
		#Range: -512 ~ 512
		oreMin = -65
		#Max height
		#Range: -512 ~ 512
		oreMax = -65

	#Overworld
	[worldgen.nether]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 0
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 8
		#Min height
		#Range: -512 ~ 512
		oreMin = -65
		#Max height
		#Range: -512 ~ 512
		oreMax = -65

	#End
	[worldgen.end]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 0
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 10
		#Min height
		#Range: -512 ~ 512
		oreMin = -65
		#Max height
		#Range: -512 ~ 512
		oreMax = -65

