
[World]

	[World.Ores]

		[World.Ores."Oil Sand"]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Silver]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Lead]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 6
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Nickel]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Cinnabar]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 1
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Sulfur]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Tin]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 6
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

		[World.Ores.Niter]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 64
			"Vein Size" = 1
			#Minimum Y spawn.
			#Range: -2032 ~ 2031
			"Min Y" = -65
			#Maximum Y spawn.
			#Range: -2032 ~ 2031
			"Max Y" = -65

